POST http://localhost:3000/api/code/save
content-type: application/json

{
    "code": "print('Hello World')", 
    "author": "Dhruv_Gheewala", 
    "output": "Hello World", 
    "language": "Python"
}

###

POST http://localhost:3000/api/code/save
content-type: application/json

{
    "code": "print('Second Post Request !!')", 
    "author": "Dhruv_Gheewala", 
    "output": "Second Post Request !!", 
    "language": "Python", 
    "visibility": "private"
}

###

POST http://localhost:3000/api/code/save
content-type: application/json

{
    "code": "print('Third Post Request !!')", 
    "author": "Dhruv_Gheewala", 
    "output": "Third Post Request !!", 
    "language": "Python", 
    "visibility": "private"
}

###

POST http://localhost:3000/api/code/save
content-type: application/json

{
    "code": "print('First Post Request !!')", 
    "author": "DhruvGheewala", 
    "output": "First Post Request !!", 
    "language": "Python", 
    "visibility": "private"
}

###

GET http://localhost:3000/api/code/view/DhruvGheewala

###

GET http://localhost:3000/api/code/view/Dhruv_Gheewala

###

PUT http://localhost:3000/api/code/view
Content-Type: application/json

{
    "author": "Dhruv_Gheewala"
}

###

PUT http://localhost:3000/api/code/view
Content-Type: application/json

{
    "author": "DhruvGheewala"
}

###

PUT http://localhost:3000/api/code/view/5ff0bd98f07fd90d6817b39e
Content-Type: application/json

{
    "author": "DhruvGheewala"
}

###

PUT http://localhost:3000/api/code/update/5ff0bd98f07fd90d6817b39e
Content-Type: application/json

{
    "author": "Changed_author",
    "code": "print('updated code')", 
    "output": "updated code", 
    "visibility": "public", 
    "language": "Python"
}

###

PUT http://localhost:3000/api/code/update/5ff0bd98f07fd90d6817b39e
Content-Type: application/json

{
    "code": "print('Reverting changes')", 
    "output": "Reverting changes"
}

###

DELETE http://localhost:3000/api/code/5ff07e6782348c3538793fb0

###

PUT http://localhost:3000/api/code/view/5ff0bd98f07fd90d6817b39e

###

PUT http://localhost:3000/api/code/view/5ff07e0882348c3538793fae

###

GET http://localhost:3000/api/code/all

###

GET http://localhost:3000/api/code//defaults/cpp

###

GET http://localhost:3000/api/code//defaults/not_avail

###

GET http://localhost:3000/api/code//defaults