POST http://localhost:3000/api/code/compile
content-type: application/json

{
    "code": "print('Second Post Request !!')", 
    "author": "a", 
    "output": "Second Post Request !!", 
    "language": "python", 
    "visibility": "private"
}

###

POST http://localhost:3000/api/code/save
content-type: application/json

{
    "code": "print('Hello World')", 
    "author": "dhiraj-01", 
    "input": "12",
    "output": "Hello World",
    "language": "Python"
}

###

POST http://localhost:3000/api/code/save
content-type: application/json

{
    "code": "print('Second Post Request !!')", 
    "author": "Dhruv_Gheewala", 
    "output": "Second Post Request !!", 
    "language": "Python", 
    "visibility": "private"
}

###

POST http://localhost:3000/api/code/save
content-type: application/json

{
    "code": "print('Third Post Request !!')", 
    "author": "Dhruv_Gheewala", 
    "output": "Third Post Request !!", 
    "language": "Python", 
    "visibility": "private"
}

###

POST http://localhost:3000/api/code/save
content-type: application/json

{
    "code": "print('First Post Request !!')", 
    "author": "DhruvGheewala", 
    "output": "First Post Request !!", 
    "language": "Python", 
    "visibility": "private"
}

###

GET http://localhost:3000/api/code/view/public/5ff2aeb0aa6eea29a44c8a79

###

GET http://localhost:3000/api/code/view/DhruvGheewala/5ff1b8ef70e1bd0a0ce3f6df

###

GET  http://localhost:3000/api/code/view/Dhruv_Gheewala

###

PUT http://localhost:3000/api/code/update/5ff0bd98f07fd90d6817b39e
Content-Type: application/json

{
    "author": "Changed_author",
    "code": "print('updated code')", 
    "output": "updated code", 
    "visibility": "public", 
    "language": "Python"
}

###

PUT http://localhost:3000/api/code/update/5ff0bd98f07fd90d6817b39e
Content-Type: application/json

{
    "code": "print('Reverting changes')", 
    "output": "Reverting changes", 
    "visibility": "Private"
}

###

DELETE http://localhost:3000/api/code/delete/5ff07e6782348c3538793fb0

###

GET http://localhost:3000/api/code/view/Dhruv_Gheewala/5ff0bd98f07fd90d6817b39e

###

GET http://localhost:3000/api/code/all

###

GET http://localhost:3000/api/code/defaults/cpp

###

GET http://localhost:3000/api/code/defaults

###

# Error Checking
POST http://localhost:3000/api/code/compile
content-type: application/json

{
    "code": "print('Second Post Request !!')", 
    "author": "a", 
    "output": "Second Post Request !!", 
    "language": "c#", 
    "visibility": "private"
}

###

GET http://localhost:3000/api/code/view/Mukesh/dsdsa

###

PUT http://localhost:3000/api/code/update/219847129
Content-Type: application/json

{
    
}

###

DELETE http://localhost:3000/api/code/delete/219847129

###

GET http://localhost:3000/api/code/defaults/not_avail

###

GET http://localhost:3000/api/code/view/DhruvGheewala/5ff0bd98f07fd90d6817b39e

###

DELETE http://localhost:3000/api/code/delete/5ff07e6782348c3538793fb0

###

PUT http://localhost:3000/api/code/update/5ff0bd98f07fd0d6817b39e
Content-Type: application/json

{
    "code": "print('Reverting changes')", 
    "output": "Reverting changes", 
    "visibility": "Private"
}

###

GET http://localhost:3000/api/code/view/DhruvGheewala/5ff0bd98f07fd90d6817b39e

###

GET http://localhost:3000/api/code/view/Dhruv_Gheewala/5ff1b8ef70e1bd0a0ce3f6df

###